# Generated by Django 4.1.1 on 2022-09-25 17:03

from django.db import migrations

def load_user_data(apps, schema_editor):
    Proyecto = apps.get_model('app', 'Proyecto')
    proyecto=Proyecto()
    proyecto.id = 0
    proyecto.nombre = "default proyecto"
    proyecto.estado = "activo"
    proyecto.save()

    User = apps.get_model('app', 'Usuario')
    user=User()
    user.id = 123456789
    user.tipoIdentificado="CC"
    user.tUsuario="admin"
    user.clave="123"
    user.nombre="Administrador"
    user.apellidos="Administrando"
    user.telefono="3001234567"
    user.correo="admin@email.com"
    user.genero="m"
    user.estado=True
    user.save()

    User = apps.get_model('app', 'Usuario')
    user2=User()
    user2.id = 1234
    user2.tipoIdentificado="CC"
    user2.tUsuario="estudiante"
    user2.clave="123"
    user2.nombre="estudiante"
    user2.apellidos="estudiantep"
    user2.telefono="3001234527"
    user2.correo="estudiante@email.com"
    user2.genero="m"
    user2.estado=True
    user2.idProyecto = proyecto
    user2.notaDefinitivaProyecto = 4.5
    user2.save()



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_user_data),
    ]
