# Generated by Django 4.1.1 on 2022-09-25 17:03

from django.db import migrations

def load_user_data(apps, schema_editor):
    User = apps.get_model('app', 'Usuario')
    user=User()
    user.id = 123456789
    user.tipoIdentificado="CC"
    user.tUsuario="admin"
    user.clave="123"
    user.nombre="Administrador"
    user.apellidos="Administrando"
    user.telefono="3001234567"
    user.correo="admin@email.com"
    user.genero="m"
    user.estado=True
    user.save()
    User = apps.get_model('app', 'Usuario')
    user2=User()
    user2.id = 123
    user2.tipoIdentificado="CC"
    user2.tUsuario="profesor"
    user2.clave="123"
    user2.nombre="profesor"
    user2.apellidos="profesorp"
    user2.telefono="3001234594"
    user2.correo="profesor@email.com"
    user2.genero="m"
    user2.estado=True
    user2.save()
    User = apps.get_model('app', 'Usuario')
    user3=User()
    user3.id = 1234
    user3.tipoIdentificado="CC"
    user3.tUsuario="estudiante"
    user3.clave="123"
    user3.nombre="estudiante"
    user3.apellidos="estudiantep"
    user3.telefono="3001234527"
    user3.correo="estudiante@email.com"
    user3.genero="m"
    user3.estado=True
    user3.save()




class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_user_data),
    ]
