# Generated by Django 4.1.1 on 2022-09-25 17:03

from django.db import migrations

def load_user_data(apps, schema_editor):
    User = apps.get_model('app', 'Usuario')
    user=User()
    user.id = 123456789
    user.tipoIdentificado="CC"
    user.tUsuario="admin"
    user.clave="123"
    user.nombre="Administrador"
    user.apellidos="Administrando"
    user.telefono="3001234567"
    user.correo="admin@email.com"
    user.genero="m"
    user.estado=True
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_user_data),
    ]
